# Generated by Django 3.0.7 on 2020-07-23 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderSource', models.CharField(choices=[('Cassandra', 'Cassandra'), ('Jana', 'Jana'), ('Kara', 'Kara'), ('RK', 'RK'), ('Megan', 'Megan'), ('Brandy', 'Brandy')], default='RK', max_length=100)),
                ('houseAccount', models.CharField(choices=[('Baycare', 'Baycare'), ('Republic', 'Republic'), ('Cater Nation', 'Cater Nation'), ('No', 'No')], default='Baycare', max_length=100)),
                ('name', models.CharField(default='NO NAME', max_length=100)),
                ('address', models.CharField(default='NO ADDRESS', max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('deliverydriver', models.CharField(default='NOT ASSIGNED', max_length=100)),
                ('deliverytime', models.TimeField(default=django.utils.timezone.now)),
                ('specialInstruction', models.CharField(default='NONE', max_length=300)),
                ('cateringAmount', models.BigIntegerField(default='0')),
                ('deliveryFee', models.BigIntegerField(default='0')),
                ('tips', models.BigIntegerField(default='0')),
                ('salesTax', models.IntegerField(default='0')),
                ('customerFeedBack', models.CharField(default='NONE', max_length=300)),
                ('onTime', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100)),
                ('deliveryStatus', models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='Not Delivered', max_length=100)),
                ('customerPaymentStatus', models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100)),
                ('employeePaymentStatus', models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100)),
                ('cateringDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('commissionAmount', models.IntegerField(default='0')),
                ('commissionStatus', models.CharField(default='NOT PAID', max_length=20)),
                ('estimatedDelivery', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
