# Generated by Django 3.0.7 on 2020-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mobile',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='order_list',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
