# Generated by Django 3.0.7 on 2020-07-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200717_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
