# Generated by Django 3.0.7 on 2020-07-23 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='order_list',
        ),
        migrations.AddField(
            model_name='post',
            name='cateringAmount',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='cateringDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='commissionAmount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='commissionStatus',
            field=models.CharField(default='NOT PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='customerFeedBack',
            field=models.CharField(default='NONE', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='customerPaymentStatus',
            field=models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='deliveryFee',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='deliveryStatus',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not Delivered', 'Not Delivered')], default='Not Delivered', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='deliverydriver',
            field=models.CharField(default='NOT ASSIGNED', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='deliverytime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='employeePaymentStatus',
            field=models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='estimatedDelivery',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='houseAccount',
            field=models.CharField(choices=[('Baycare', 'Baycare'), ('Republic', 'Republic'), ('Cater Nation', 'Cater Nation'), ('No', 'No')], default='Baycare', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='onTime',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='orderSource',
            field=models.CharField(choices=[('Cassandra', 'Cassandra'), ('Jana', 'Jana'), ('Kara', 'Kara'), ('RK', 'RK'), ('Megan', 'Megan'), ('Brandy', 'Brandy')], default='RK', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='salesTax',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='specialInstruction',
            field=models.CharField(default='NONE', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='tips',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='NO ADDRESS', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='NO NAME', max_length=100),
        ),
    ]
