# Generated by Django 3.0.7 on 2020-07-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pro_pic',
            new_name='image',
        ),
    ]
